inherit_from: .rubocop_todo.yml

Rails:
  Enabled: true

AllCops:
  TargetRailsVersion: 4
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - '.bundle/**/*'
    - 'app/admin/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'vendor/**/*'
    - 'test/**/*'
    - 'lib/tasks/**/*'
    - 'Guardfile'
    - 'Gemfile'
    - 'Capfile'
