AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - '.bundle/**/*'
    - 'app/admin/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'test/**/*'
    - 'vendor/**/*'

Documentation:
  Enabled: false