inherit_from: .rubocop_todo.yml


AllCops:
  RunRailsCops: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - '.bundle/**/*'
    - 'app/admin/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'vendor/**/*'
