# service configuration for our database
db:
  # use the preferred version of the official Postgres image
  # see https://hub.docker.com/_/postgres/
  image: postgres:9.4.5

  # persist the database between containers by storing it in a volume
  volumes:
    - docker-example-postgres:/var/lib/postgresql/data

# service configuration for our web server
web:
  # set the build context to the root of the Rails app
  build: .

  # sources environment variable configuration for our app
  env_file: .env

  # makes the web container aware of the app container
  links:
    - db

  # rely on the RAILS_ENV value of the host machine
  environment:
    RAILS_ENV: $RAILS_ENV

  # expose the port we configured Nginx to bind to
  ports:
    - "3000:3000"
