# service configuration for our database
postgres:
  container_name: seatshare-postgres
  image: postgres:9.4
  ports:
    - "55432:5432"

# service configuration for our web server
web:
  container_name: seatshare-web
  build: .
  command: rails server -p 3000 -b '0.0.0.0'
  env_file: .env
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - postgres
