development:
  adapter: postgresql
  encoding: unicode
  database: seatshare_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: seatshare_test
  pool: 5

production:
  adapter: postgresql
  pool: 5